HietalasALMBank/Models/Account.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HietalasALMBank.Models
{
    public class Account
    {
        public string AccountNumber { get; set; }
        public double Balance { get; set; }

        public bool Transfer(Account account, double amount)
        {
            if (Balance - amount < 0)
            {
                return false;
            }

            Balance -= amount;
            account.Balance += amount;
            return true;
        }
    }
}

HietalasALMBank/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HietalasALMBank.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }
        public string Firstname { get; set; }
        public string Lastname  { get; set; }
        public List<Account> AccountList { get; set; }
    }
}

HietalasALMBank/Models/ErrorViewModel.cs
using System;

namespace HietalasALMBank.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HietalasALMBank/Models/TransferViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HietalasALMBank.Models
{
    public class TransferViewModel
    {

        [Required(ErrorMessage = "Ett från-kontonummer är obligatoriskt")]
        public string FromAccountNumber { get; set; }
        [Required(ErrorMessage = "Ett till-kontonummer är obligatoriskt")]
        public string ToAccountNumber { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Minsta överföringen är 1kr")]
        public double Amount { get; set; }

    }
}

HietalasALMBank/Models/WithdrawDepositViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HietalasALMBank.Models
{
    public class WithdrawDepositViewModel
    {
        public double Amount { get; set; }
        public string AccountNumber { get; set; }
    }
}

HietalasALMBank/Controllers/BankAccountController.cs
using System;
using System.Collections.Generic;
using HietalasALMBank.Models;
using HietalasALMBank.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace HietalasALMBank.Controllers
{
    public class BankAccountController : Controller
    {
        private List<Customer> customers;
        private BankRepository bankRepo;

        public BankAccountController()
        {
            customers = Startup.Dummydata;
            bankRepo = new BankRepository();
        }

        public IActionResult WithdrawAndDeposit(string accountNumber = null, double amount = 0)
        {
            WithdrawDepositViewModel model = new WithdrawDepositViewModel() { AccountNumber = accountNumber, Amount = amount };
            return View(model);
        }

        public IActionResult Deposit(string accountNumber, string amount)
        {
            string errorMessage = CheckInputs(accountNumber, amount);

            if (errorMessage == null)
            {
                Account account = bankRepo.GetAccount(accountNumber);
                var newBalance = bankRepo.Deposit(account, amount);
                TempData["responseSuccess"] = $"Konto: {accountNumber}, Nytt saldo: { newBalance }";
                return RedirectToAction("WithdrawAndDeposit", new { accountNumber });
            }
            else
            {
                TempData["responseFailed"] = errorMessage;
                return RedirectToAction("WithdrawAndDeposit", new { accountNumber });
            }
        }

        public IActionResult Withdraw(string accountNumber, string amount)
        {
            string errorMessage = CheckInputs(accountNumber, amount);
                                 
            if (errorMessage == null)
            {
                Account account = bankRepo.GetAccount(accountNumber);

                if (bankRepo.CheckIfWithdrawIsOk(account.Balance, amount) == false)
                {
                    errorMessage = $"Saldo måste vara högre än summa. Aktuellt saldo: {account.Balance}";
                }
                else
                {
                    var newBalance = bankRepo.Withdraw(account, amount);
                    TempData["responseSuccess"] = $"Konto: {accountNumber}, Nytt saldo: { newBalance }";
                    return RedirectToAction("WithdrawAndDeposit", new { accountNumber });
                }
            }
            TempData["responseFailed"] = errorMessage;
            return RedirectToAction("WithdrawAndDeposit", new { accountNumber });
        }


        public string CheckInputs(string accountNumber, string amount)
        {
            string errorMessage = null;

            if (bankRepo.CheckInputAmount(amount) == false)
            {
                errorMessage = $"Felaktigt inmatning {amount}: Belopp måste vara över 0 och siffror";
            }

            Account account = bankRepo.GetAccount(accountNumber);

            if (account == null)
            {
                errorMessage = $"Hittar inget konto med kontonummer: {accountNumber}";
            }

            return errorMessage;
        }
    }
}

HietalasALMBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HietalasALMBank.Models;

namespace HietalasALMBank.Controllers
{
    public class HomeController : Controller
    {
        private List<Customer> data;

        public HomeController()
        {
            data = Startup.Dummydata;
        }

        public IActionResult Index()
        {
            return View(data);
        }      

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HietalasALMBank/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HietalasALMBank.Models;
using HietalasALMBank.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace HietalasALMBank.Controllers
{
    public class TransferController : Controller
    {
        public IActionResult Transfer()
        {
            TransferViewModel model = new TransferViewModel() { FromAccountNumber = "", ToAccountNumber = "", Amount = 0 };
            return View(model);
        }

        [HttpPost]
        public IActionResult Transfer(TransferViewModel model)
        {
         
            if (ModelState.IsValid)
            {
                if (model.FromAccountNumber == model.ToAccountNumber)
                {
                    TempData["response"] = "Du kan inte överföra mellan samma konto";
                    return View(model);
                }

                BankRepository repo = new BankRepository();
                Account from = repo.GetAccount(model.FromAccountNumber);
                Account to = repo.GetAccount(model.ToAccountNumber);

                if (from == null || to == null)
                {
                    if (from == null)
                    {
                        TempData["fromNull"] = $"Kontonummret {model.FromAccountNumber} kunde inte hittas";
                    }
                    if (to == null)
                    {
                        TempData["toNull"] = $"Kontonummret {model.ToAccountNumber} kunde inte hittas";
                    }
                    
                    return View(model);
                }

                bool transferSuccess = from.Transfer(to, model.Amount);

                if (transferSuccess)
                {
                    TempData["response"] = $"Överföring genomförd! Konto nr:{from.AccountNumber} summa: {from.Balance} Konto nr:{to.AccountNumber} summa: {to.Balance}";
                }
                else
                {
                    TempData["response"] = $"Du kan inte överföra mer pengar än det finns på kontot! Konto nr:{from.AccountNumber} summa: {from.Balance}";
                }

            }
            return View(model);
        }
    }
}

HietalasALMBank/Views/BankAccount/WithdrawAndDeposit.cshtml
@{
    ViewData["Title"] = "WithdrawAndDeposit";
}

@model HietalasALMBank.Models.WithdrawDepositViewModel


<h2>Uttag och insättning</h2>

<form asp-route-accountNumber="" asp-route-amount="" method="post">
    <span class="bg-danger"> @TempData["responseFailed"]</span>
    <span class="bg-success"> @TempData["responseSuccess"]</span><br />

    Kontonummer:  <br />

    <input type="text" name="AccountNumber" value=@Model.AccountNumber /><br />

    Summa:<br />

    <input type="text" name="Amount" value="@Model.Amount" /><br /><br />

    <input class="btn-success" type="submit" value="Insättning" name="Deposit"  formaction="Deposit" />
    <input class="btn-danger"  type="submit" value="Uttag"      name="Withdraw" formaction="Withdraw" />
</form>

HietalasALMBank/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


@model List<HietalasALMBank.Models.Customer>


<h1>Mikael Hietalas ALM Bank</h1>

<div class="container">      
    <table class="table">
        <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Account ID</th>
                <th>Balance</th>
                <th>Account ID</th>
                <th>Balance</th>
            </tr>

            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Firstname</td>
                    <td>@customer.Lastname</td>
                    @foreach (var account in customer.AccountList)
                    {
                        <td>@account.AccountNumber</td>
                        <td>@account.Balance :-</td>
                    }
                </tr>
            }

        </thead>
        <tbody></tbody>
    </table>
</div>

HietalasALMBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HietalasALMBank</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HietalasALMBank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="BankAccount" asp-action="WithdrawAndDeposit">Uttag och insättning</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Transfer" asp-action="Transfer">Överföring</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - HietalasALMBank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HietalasALMBank/Views/Transfer/Transfer.cshtml
@model TransferViewModel
@{
    ViewData["Title"] = "Transfer";
}

<div class="container">
    <h2>Överföringar</h2>

    <div asp-validation-summary="All"></div>
    <span>@TempData["response"]</span>
    
    
    <form asp-action="Transfer" method="post">

        <label>Från konto</label>
        <input type="text" asp-for="@Model.FromAccountNumber" value="@Model.FromAccountNumber" />
        <span>@TempData["fromNull"]</span><br />

        <label>Till konto</label>
        <input type="text" asp-for="@Model.ToAccountNumber" value="@Model.ToAccountNumber" />
        <span>@TempData["toNull"]</span><br />

        <label>Summa konto</label>
        <input min="1" type="text" asp-for="@Model.Amount" value="@Model.Amount" /><br />

        <input type="submit" value="Skicka överföring" />

    </form>

</div>